[package]
name = "CAGrepeat-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
figlet-rs = "0.1.5"
plotpy = "1.13.0"
tokio = { version = "1.47.1", features = ["full"] }
